export const habitSeedData = [
  { name: 'Exercise',                       description: 'Go for a run.',                                      authorId: 1     },
  { name: 'Read',                           description: 'Read a book for 30 minutes.',                        authorId: 2     },
  { name: 'Drink Water',                    description: 'Drink 8 glasses of water.',                          authorId: 1     },
  { name: 'Meditate',                       description: 'Meditate for 10 minutes.',                           authorId: 3     },
  { name: 'Cook a Healthy Meal',            description: 'Prepare a nutritious meal.',                         authorId: 2     },
  { name: 'Write in Journal',               description: 'Write down thoughts and feelings.',                  authorId: 3     },
  { name: 'Practice Gratitude',             description: 'Write down three things you\'re grateful for.',      authorId: 1     },
  { name: 'Learn Something New',            description: 'Spend 30 minutes learning a new skill.',             authorId: 2     },
  { name: 'Yoga',                           description: 'Do a yoga session.',                                 authorId: 1     },
  { name: 'Listen to Podcast',              description: 'Listen to an educational podcast.',                  authorId: 3     },
  { name: 'Stretch',                        description: 'Stretch your muscles.',                              authorId: 1     },
  { name: 'Practice Mindfulness',           description: 'Practice being present in the moment.',              authorId: 3     },
  { name: 'Take a Walk',                    description: 'Take a walk outdoors.',                              authorId: 1     },
  { name: 'Review Goals',                   description: 'Review your short-term and long-term goals.',        authorId: 2     },
  { name: 'Practice a Musical Instrument',  description: 'Practice playing a musical instrument.',             authorId: 3     },
  { name: 'Call a Friend',                  description: 'Call a friend or family member.',                    authorId: 1     },
  { name: 'Plan Tomorrow',                  description: 'Plan your tasks and schedule for tomorrow.',         authorId: 2     },
  { name: 'Declutter',                      description: 'Spend 15 minutes decluttering a space.',             authorId: 3     },
  { name: 'Do a Puzzle',                    description: 'Solve a puzzle.',                                    authorId: 1     },
  { name: 'Watch a Documentary',            description: 'Watch an informative documentary.',                  authorId: 2     },
];