version: '3.8'

services:
  database:
    image: postgres:13
    container_name: ares-database-postgres
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - ares-network
    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ares-backend
    environment: 
      - NODE_ENV=development
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8089:8089"
    depends_on:
      - database
    networks:
      - ares-network


  webif:
    build: 
      context: ./web-interface
      dockerfile: Dockerfile
    container_name: ares-webif
    environment: 
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8089
    volumes:
      - ./webif:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - ares-network

networks:
  ares-network:
    driver: bridge

volumes:
  postgres_data: