export const habitSeedData = [
  { name: 'Exercise',                       description: 'Go for a run.',                                    habitSheetId: 1,    authorId: 1     },
  { name: 'Read',                           description: 'Read a book for 30 minutes.',                      habitSheetId: 2,    authorId: 2     },
  { name: 'Drink Water',                    description: 'Drink 8 glasses of water.',                        habitSheetId: 1,    authorId: 1     },
  { name: 'Meditate',                       description: 'Meditate for 10 minutes.',                         habitSheetId: 3,    authorId: 3     },
  { name: 'Cook a Healthy Meal',            description: 'Prepare a nutritious meal.',                       habitSheetId: 2,    authorId: 2     },
  { name: 'Write in Journal',               description: 'Write down thoughts and feelings.',                habitSheetId: 3,    authorId: 3     },
  { name: 'Practice Gratitude',             description: 'Write down three things you\'re grateful for.',    habitSheetId: 1,    authorId: 1     },
  { name: 'Learn Something New',            description: 'Spend 30 minutes learning a new skill.',           habitSheetId: 2,    authorId: 2     },
  { name: 'Yoga',                           description: 'Do a yoga session.',                               habitSheetId: 1,    authorId: 1     },
  { name: 'Listen to Podcast',              description: 'Listen to an educational podcast.',                habitSheetId: 3,    authorId: 3     },
  { name: 'Stretch',                        description: 'Stretch your muscles.',                            habitSheetId: 1,    authorId: 1     },
  { name: 'Practice Mindfulness',           description: 'Practice being present in the moment.',            habitSheetId: 3,    authorId: 3     },
  { name: 'Take a Walk',                    description: 'Take a walk outdoors.',                            habitSheetId: 1,    authorId: 1     },
  { name: 'Review Goals',                   description: 'Review your short-term and long-term goals.',      habitSheetId: 2,    authorId: 2     },
  { name: 'Practice a Musical Instrument',  description: 'Practice playing a musical instrument.',           habitSheetId: 3,    authorId: 3     },
  { name: 'Call a Friend',                  description: 'Call a friend or family member.',                  habitSheetId: 1,    authorId: 1     },
  { name: 'Plan Tomorrow',                  description: 'Plan your tasks and schedule for tomorrow.',       habitSheetId: 2,    authorId: 2     },
  { name: 'Declutter',                      description: 'Spend 15 minutes decluttering a space.',           habitSheetId: 3,    authorId: 3     },
  { name: 'Do a Puzzle',                    description: 'Solve a puzzle.',                                  habitSheetId: 1,    authorId: 1     },
  { name: 'Watch a Documentary',            description: 'Watch an informative documentary.',                habitSheetId: 2,    authorId: 2     },
];